query delivery {
  delivery {
    pending {
      _id
      count
      total
      items{
        user{
          firstName
          lastName
          phone
          id
        }
        vendor{
          firstName
          lastName
          restaurant
          phone
        }
        address{
          firstName
          lastName
          address
          phone
        }
        amount{
          subtotal
          discount
          shipping
          tax
          total
        }
      }
    }
    out {
      _id
      count
      total
      items{
        user{
          firstName
          lastName
          phone
          id
        }
        vendor{
          firstName
          lastName
          restaurant
          phone
        }
        address{
          firstName
          lastName
          address
          phone
        }
        amount{
          subtotal
          discount
          shipping
          tax
          total
        }
      }
    }
    delivered {
      _id
      count
      total
      items{
        user{
          firstName
          lastName
          phone
          id
        }
        vendor{
          firstName
          lastName
          restaurant
          phone
        }
        address{
          firstName
          lastName
          address
          phone
        }
        amount{
          subtotal
          discount
          shipping
          tax
          total
        }
      }
    }
    cancelled {
      _id
      count
      total
      items{
        user{
          firstName
          lastName
          phone
          id
        }
        vendor{
          firstName
          lastName
          restaurant
          phone
        }
        address{
          firstName
          lastName
          address
          phone
        }
        amount{
          subtotal
          discount
          shipping
          tax
          total
        }
      }
    }
    all {
      _id
      count
      total
      items{
        user{
          firstName
          lastName
          phone
          id
        }
        vendor{
          firstName
          lastName
          restaurant
          phone
        }
        address{
          firstName
          lastName
          address
          phone
        }
        amount{
          subtotal
          discount
          shipping
          tax
          total
        }
      }
    }
  }
  settings{
    orderStatuses
  }
}
