query orders(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $vendor: String
  $user: String
) {
  orders(
    page: $page
    vendor: $vendor
    skip: $skip
    limit: $limit
    search: $search
    sort: $sort
  ) {
    data {
      id
      orderNo
      otp
      amount {
        qty
        subtotal
        total
        shipping
        discount
      }
      delivery {
        otp
        finish {
          lat
          lng
        }
      }
      status
      items {
        name
        slug
        img
        rate
        qty
      }
      uid {
        phone
        firstName
        lastName
      }
      address {
        firstName
        lastName
        address
        town
        city
        zip
        coords {
          lat
          lng
        }
      }
      createdAt
      updatedAt
    }
  }
}
