query todaysStatus {
  todaysStatus {
    _id
    amount
    count
    items {
      address {
        firstName
        lastName
        address
        coords {
          lat
          lng
        }
      }
      amount {
        subtotal
        discount
        shipping
        total
      }
      vendor {
        restaurant
      }
      otp
      orderNo
      createdAt
    }
  }
}
